import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '../../components/Navbar'
import Hero from '../../components/Hero'
import Client from '../../components/Client'
import Services from '../../components/Services'
import About from '../../components/About'
import Pricing from '../../components/Pricing'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">

        <div class="bg-gray-50">
          <Navbar />
          <Hero />
          <Client/>
          <Services/>
          <About/>
          <Pricing />
        </div>

      </main>
    </>
  )
}
