import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '@sections/Navbar'
import Hero from '@sections/Hero'
import Client from '@sections/Client'
import Services from '@sections/Services'
import About from '@sections/About'
import Pricing from '@sections/Pricing'
import News from '@sections/News'
import Footer from '@sections/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <div className="bg-gray-50">
          <Navbar />
          <Hero />
          <Client/>
          <Services/>
          <About/>
          <Pricing />
          <News/>
          <Footer/>
        </div>

      </main>
    </>
  )
}
